// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF3SpJ-CJaZWzQdzQooo_kyVDkmgYyh-U',
    appId: '1:987233483863:web:50a5064bfe72f5a4723712',
    messagingSenderId: '987233483863',
    projectId: 'flutter-chat-app-814b4',
    authDomain: 'flutter-chat-app-814b4.firebaseapp.com',
    storageBucket: 'flutter-chat-app-814b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcMjSK0XNHf22cEu2QWLxOJzAbkHDsH74',
    appId: '1:987233483863:android:4cefe30f52fbc3bd723712',
    messagingSenderId: '987233483863',
    projectId: 'flutter-chat-app-814b4',
    storageBucket: 'flutter-chat-app-814b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8FdMsh5Ueu5EAu88FKBhOFjuX44qSfxE',
    appId: '1:987233483863:ios:7e23bed16441897f723712',
    messagingSenderId: '987233483863',
    projectId: 'flutter-chat-app-814b4',
    storageBucket: 'flutter-chat-app-814b4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8FdMsh5Ueu5EAu88FKBhOFjuX44qSfxE',
    appId: '1:987233483863:ios:ebd43e03b584da6e723712',
    messagingSenderId: '987233483863',
    projectId: 'flutter-chat-app-814b4',
    storageBucket: 'flutter-chat-app-814b4.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
